import os
import shutil
import uuid
from pathlib import Path

from app.core.config import settings


ACCOUNT_SUBDIRECTORIES = ("browser-profile", "screenshots", "logs", "exports")


def initialize_account_storage(account_id: uuid.UUID, profile_key: str) -> Path:
    """Create a private, account-scoped storage tree.

    profile_key is generated by the server and is never derived from a user-visible
    nickname, preventing directory collisions and accidental cross-account reuse.
    """
    account_root = settings.account_data_root / str(account_id) / profile_key
    account_root.mkdir(mode=0o700, parents=True, exist_ok=False)
    for name in ACCOUNT_SUBDIRECTORIES:
        (account_root / name).mkdir(mode=0o700)
    os.chmod(account_root, 0o700)
    return account_root


def account_storage_path(account_id: uuid.UUID, profile_key: str) -> Path:
    root = settings.account_data_root / str(account_id) / profile_key
    if not root.is_dir():
        raise FileNotFoundError("知乎账号独立存储目录不存在")
    return root


def remove_empty_account_storage(account_id: uuid.UUID) -> None:
    """Best-effort cleanup used only when account creation fails before use."""
    root = settings.account_data_root / str(account_id)
    try:
        root.rmdir()
    except OSError:
        return


def delete_account_storage(account_id: uuid.UUID, profile_key: str) -> None:
    """Remove one exact account tree after its database row is deleted."""
    base = settings.account_data_root.resolve()
    account_root = (base / str(account_id)).resolve()
    profile_root = (account_root / profile_key).resolve()
    if account_root.parent != base or account_root.name != str(account_id):
        raise ValueError("知乎账号存储目录校验失败")
    if profile_root.parent != account_root or profile_root.name != profile_key:
        raise ValueError("知乎账号资料目录校验失败")
    if profile_root.is_dir():
        shutil.rmtree(profile_root)
    try:
        account_root.rmdir()
    except OSError:
        pass
