import os
import uuid
from pathlib import Path

from app.core.config import settings


ACCOUNT_SUBDIRECTORIES = ("browser-profile", "screenshots", "logs", "exports")


def initialize_account_storage(account_id: uuid.UUID, profile_key: str) -> Path:
    """Create a private, account-scoped storage tree.

    profile_key is generated by the server and is never derived from a user-visible
    nickname, preventing directory collisions and accidental cross-account reuse.
    """
    account_root = settings.account_data_root / str(account_id) / profile_key
    account_root.mkdir(mode=0o700, parents=True, exist_ok=False)
    for name in ACCOUNT_SUBDIRECTORIES:
        (account_root / name).mkdir(mode=0o700)
    os.chmod(account_root, 0o700)
    return account_root


def remove_empty_account_storage(account_id: uuid.UUID) -> None:
    """Best-effort cleanup used only when account creation fails before use."""
    root = settings.account_data_root / str(account_id)
    try:
        root.rmdir()
    except OSError:
        return

